---
apiVersion: v1
kind: Service
metadata:
  name: avalanche-service
  namespace: store-load-test
  labels:
    app: avalanche-app
spec:    
  selector:
    app: avalanche-app
  ports:
    - protocol: TCP
      port: 2112
      targetPort: 2112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  namespace: store-load-test
  labels:
    app: avalanche-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: avalanche-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /stats
        prometheus.io/port: "2112"     
      labels:
        app: avalanche-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: avalanche-app
        image: docker.internal.sysdig.com/avalanche:goldman-beacon-10
        resources:
          limits:
            cpu: 5
            memory: 10Gi
          requests:
            cpu: 5
            memory: 10Gi
        args:
        - --metric-count=1000
        - --series-count=1000
        - --port=9001 
        - --series-interval=36000 
        - --metric-interval=3600000 
        - --value-interval=10 
        - --remote-url=https://stefan-beacon-perf-kops-fre-lb-52c5173c29c4d9ca.elb.us-east-1.amazonaws.com/prometheus/remote/write
        - --remote-requests-count=10000000
        - --remote-write-interval=80000ms
        - --const-label=instance=$(INSTANCE)
        - --remote-batch-size=5000
        - --remote-read-batch-size=0
        - --remote-read-requests-count=0
        - --remote-read-interval=10s
        - --http-bearer-token=1da28aff-eb31-47d9-b0c7-5ad4f9e323ae
        ports:
        - containerPort: 9001
        - containerPort: 2112
        env: 
          - name: INSTANCE
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
        - name: avalanche-pull-secret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: store-load-test
  name: ingress-avalanche
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: avalanche-service
              servicePort: 2112
